[package]
name = "util"
version = "0.1.0"
edition = "2021"

[lib]
name = "util"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { workspace = true }
md5 = { workspace = true }
chrono = { workspace = true }